name: Build

on:
  push:
    branches: [ main, test_javaversions]
  pull_request:
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        java: [8, 11, 17, 19]

    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version:  ${{ matrix.java }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Check spotless
        run: |
          ./gradlew install
          cd build/install/fingerprinting/bin
          ./fingerprinting --api-key= ${{ secrets.GE_API_KEY }} --url= ${{ secrets.GE_URL }} --max-duration=1000 --max-builds=5000 --project=nowinandroid 

